### PR TITLE
Add Bigfont and Anavrins' ChaCha20,MD5,SHA-1 and changed SHA-256

### PR DESCRIPTION
**Pull request by Commandcracker**
- [x] I have read the [contribution guidelines](./CONTRIBUTING.md).
- [x] I agree to release my contributions under the [CC-BY-SA](./LICENSE.md) license.

### CODE REVIEW

**Comment by tomodachi94** [comment]
@Commandcracker I am confused, why are the hashing libraries separated?

**Comment by Commandcracker** [comment]
> @Commandcracker I am confused, why are the hashing libraries separated?

separated in the README.md or separated in libraries ?

if you ment **separated in libraries** then the awnser is Anavrins created them like this
if you ment **separated in the README.md** then I could rearange them

**Comment by tomodachi94** [comment]
I meant to ask why you separated them in the Readme.

Is there a single forum post that links to all of the libraries? It seems kind of cluttered to have them all on the list.

**Comment by Commandcracker** [comment]
> Is there a single forum post that links to all of the libraries? It seems kind of cluttered to have them all on the list.

[anavrins's user Page](http://www.computercraft.info/forums2/index.php?/user/12870-anavrins/)

> I meant to ask why you separated them in the Readme.

A section for encryption and hashing would probably make it moor clean

**Comment by tomodachi94** [comment]
I think we should keep the original "Anavrins' hashing libraries" entry and have all of those hashing libraries be a sub-entry to increase readability.

**Comment by tomodachi94** [comment]
Alright, this looks awesome! Thank you!

**Pull request merged**
